//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinkDNS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hostfiles/blocklist")]
        public string BlocklistFolderLocation {
            get {
                return ((string)(this["BlocklistFolderLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hostfiles/whitelist")]
        public string WhitelistFolderLocation {
            get {
                return ((string)(this["WhitelistFolderLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("config/blocklist.ini")]
        public string BlocklistIniLocation {
            get {
                return ((string)(this["BlocklistIniLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("config/whitelist.ini")]
        public string WhitelistIniLocation {
            get {
                return ((string)(this["WhitelistIniLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("config/userblocklist.txt")]
        public string UserBlocklistIniLocation {
            get {
                return ((string)(this["UserBlocklistIniLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("config/userwhitelist.txt")]
        public string UserWhitelistIniLocation {
            get {
                return ((string)(this["UserWhitelistIniLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hostfiles/blocklist/combined-blocklist.txt")]
        public string CombinedBlocklistFileLocation {
            get {
                return ((string)(this["CombinedBlocklistFileLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hostfiles/whitelist/combined-whitelist.txt")]
        public string CombinedWhitelistFileLocation {
            get {
                return ((string)(this["CombinedWhitelistFileLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("logs")]
        public string LogsFolderLocation {
            get {
                return ((string)(this["LogsFolderLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("config")]
        public string ConfigFolderLocation {
            get {
                return ((string)(this["ConfigFolderLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("resolvers")]
        public string ResolversFolderLocation {
            get {
                return ((string)(this["ResolversFolderLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hostfiles")]
        public string HostFilesFolderLocation {
            get {
                return ((string)(this["HostFilesFolderLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("backup")]
        public string BackupFolderLocation {
            get {
                return ((string)(this["BackupFolderLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("taskschedules/taskscheduler.ini")]
        public string TaskSchedulerIniLocation {
            get {
                return ((string)(this["TaskSchedulerIniLocation"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableDiskLogging {
            get {
                return ((bool)(this["EnableDiskLogging"]));
            }
            set {
                this["EnableDiskLogging"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("taskschedules")]
        public string TaskScheduleFolderLocation {
            get {
                return ((string)(this["TaskScheduleFolderLocation"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int LogExpiryInDays {
            get {
                return ((int)(this["LogExpiryInDays"]));
            }
            set {
                this["LogExpiryInDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PendingDNSCryptRestart {
            get {
                return ((bool)(this["PendingDNSCryptRestart"]));
            }
            set {
                this["PendingDNSCryptRestart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\dnscrypt-proxy")]
        public string DNSCryptInstallationLocation {
            get {
                return ((string)(this["DNSCryptInstallationLocation"]));
            }
            set {
                this["DNSCryptInstallationLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Information")]
        public string TraceLoggerThreshold {
            get {
                return ((string)(this["TraceLoggerThreshold"]));
            }
            set {
                this["TraceLoggerThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableDNSCryptRestartWarning {
            get {
                return ((bool)(this["DisableDNSCryptRestartWarning"]));
            }
            set {
                this["DisableDNSCryptRestartWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RestartDNSCryptAfterUpdatingLists {
            get {
                return ((bool)(this["RestartDNSCryptAfterUpdatingLists"]));
            }
            set {
                this["RestartDNSCryptAfterUpdatingLists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrimaryNetworkAdapter {
            get {
                return ((string)(this["PrimaryNetworkAdapter"]));
            }
            set {
                this["PrimaryNetworkAdapter"] = value;
            }
        }
    }
}
